# Generated by Django 4.2.6 on 2023-10-16 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='address',
            field=models.CharField(default='Somewhere, in a galaxy far far away...', max_length=255),
        ),
    ]
