# Generated by Django 4.2.6 on 2023-10-16 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuapp', '0002_restaurant_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='name',
            field=models.CharField(default='No Dish Name Yet (Placeholder)', max_length=255),
            preserve_default=False,
        ),
    ]
